Adding inconsistentStructName change
mattermost/mattermost-govet pull request #3
Opened 2020-01-03 12:27 UTC by jespino

2020-01-04 04:17 UTC, agnivade requested changes
I see that you have been busy in your vacation :)

2020-01-04 04:17 UTC, agnivade commented on inconsistentStructName/inconsistentStructName.go
> +package inconsistentStructName
It's not really a struct name. The spec calls it a receiver: https://golang.org/ref/spec#Method_declarations. I would suggest `inconsistentReceiverName`.

2020-01-04 04:17 UTC, agnivade commented on inconsistentStructName/inconsistentStructName.go
> +	Doc:  "check for inconsistent struct name in the methods definition",
check for inconsistent receiver names in the methods of a struct

2020-01-04 04:17 UTC, agnivade commented on inconsistentStructName/inconsistentStructName.go
> +	firstVarNameForType := make(map[string]firstVarName)
firstReceiverNameForType

2020-01-04 04:17 UTC, agnivade commented on inconsistentStructName/inconsistentStructName.go
> +						varName := field.Names[0].Name
Check for len > 0

2020-01-04 04:17 UTC, agnivade commented on inconsistentStructName/inconsistentStructName.go
> +						if _, exists := firstVarNameForType[typeIdent.Name]; !exists {
We are duplicating the map access here. I would suggest to do it like:
```go
mapEntry, ok := firstVarNameForType[typeIdent.Name]
if !ok {
	firstVarNameForType[typeIdent.Name] = firstVarName{
			Name: varName,
			Node: node,
		}
	return true
}
if mapEntry.Name != varName {
	// use mapEntry.Name
}
```

2020-01-04 04:17 UTC, agnivade commented on inconsistentStructName/inconsistentStructName.go
> +							pass.Reportf(node.Pos(), "Different variable name used for the struct %s in different methods, using %s here but was named as %s before at %s", typeIdent.Name, varName, otherVarName, otherVarP
Different receiver name .. : using %s here ...

2020-01-04 04:17 UTC, agnivade commented on inconsistentStructName/inconsistentStructName.go
> +					typeIdent, ok := field.Type.(*ast.Ident)
I would re-arrange the checks from StarExpr first. Then the check for *ast.Ident becomes easy.

```go
field := funDecl.Recv.List[0]
expr := field.Type
starExpr, ok := field.Type.(*ast.StarExpr)
if ok {
	expr = starExpr.X
}
typeIdent, ok := expr.(*ast.Ident)
if !ok {
	return false
}
// use typeIdent from here
```

2020-01-07 11:19 UTC, jespino commented on inconsistentStructName/inconsistentStructName.go
> +						varName := field.Names[0].Name
That is already checked in the first if

2020-01-07 11:20 UTC, jespino commented
I think I addressed everything here.

2020-01-07 11:51 UTC, agnivade approved these changes
LGTM

2020-01-07 11:55 UTC, merged