HTTP verb constant support for net/http
mattermost/mattermost-govet pull request #39
Opened 2024-07-08 19:50 UTC by enzowritescode

#### Summary
- Update `.gitignore`
- Add instructions to `README.md` for running locally
- Update `openApiSync/openApiSync.go` to support `net/http` HTTP verb constants in

#### Ticket Link
N/A

2024-07-08 20:24 UTC, lieut-data requested changes
Thanks, @enzowritescode! This looks good -- would you be willing to update the unit test data at https://github.com/mattermost/mattermost-govet/blob/2703fdd901910a9f90953ef656ad88f0b7c49bff/openApiSync/testdata/src/api/users.go#L12-L13 with one of these new constants so we can keep this working going forward?

2024-07-09 13:37 UTC, lieut-data commented on openApiSync/testdata/src/api/users.go
> +	a.BaseRoutes.Groups.Handle("/{group_id:[A-Za-z0-9]+}/{syncable_type:teams|channelz}/{syncable_id:[A-Za-z0-9]+}/link", a.ApiSessionRequired(getUsersByIds)).Methods(http.MethodPost) // want `Cannot fi
Thanks, @enzowritescode -- sorry to bug, but could we have one with "POST" and one with `http.MethodPost`? That way we test both the backwards compatibility and the "new way forward", allowing this tool to continue working with previous release branches.

2024-07-09 14:11 UTC, enzowritescode commented on openApiSync/testdata/src/api/users.go
> +	a.BaseRoutes.Groups.Handle("/{group_id:[A-Za-z0-9]+}/{syncable_type:teams|channelz}/{syncable_id:[A-Za-z0-9]+}/link", a.ApiSessionRequired(getUsersByIds)).Methods(http.MethodPost) // want `Cannot fi
@lieut-data gotcha! Updated.

2024-07-09 14:44 UTC, lieut-data approved these changes
Sweet, thanks @enzowritescode!

2024-07-09 14:45 UTC, lieut-data commented
@phoinixgrr, would you be in a position to help give this a second review and comment on the `goreleaser` changes?

2024-07-11 05:37 UTC, phoinixgrr commented
No objections merging this. 🚀 
Tests fails though https://github.com/mattermost/mattermost-govet/actions/runs/9858575330/job/27220277302?pr=39

Additionally, we should consider removing goreleaser in the future. I'll create an internal ticket to address this.

2024-07-11 14:33 UTC, enzowritescode commented
@phoinixgrr looks like that is another flag that was also removed. I'll fix it.
https://goreleaser.com/deprecations/#-rm-dist

2024-07-11 14:37 UTC, phoinixgrr approved these changes

2024-07-11 14:39 UTC, merged