implemented swagger api checker
mattermost/mattermost-govet pull request #5
Opened 2020-03-16 15:54 UTC by reflog

#### Summary
Added openApiSync analyzer. It does the following:

1. Parses our swagger schema (supplied via -openApiSync.spec param)
1. Finds all our route definitions (including subrouters)
1. Validates that the comment in the struct matches the handler prefix
1. Validates that handler prefix is present in Swagger
1. Validates that handler is registered with proper HTTP method in Swagger

2020-03-17 13:15 UTC, reflog commented
@jespino I'v reduced the Hadouken effect. Can you review please?

2020-03-23 12:07 UTC, jespino commented on openApiSync/openApiSync.go
> +		return nil, errors.Wrapf(err, "Unable to parse swagger")
nit: Maybe a more clear error message here. Something like `Unable to parse spec file. Expected OpenAPI3 format.`

2020-03-23 12:11 UTC, jespino commented on openApiSync/openApiSync.go
> +	for _, initFunc := range initFunctions {
This loop looks really unnefficient, you scanning the whole AST for all the files for every single function, you can extract that loop here, process the AST only one time, and execute the logic around the functions in this same pass.

2020-03-23 12:15 UTC, jespino commented on openApiSync/openApiSync.go
> +				aexpr, ok := expr.X.(*ast.CallExpr).Fun.(*ast.SelectorExpr).X.(*ast.CallExpr)
This looks a bit fragile, but because is really tided to our source code I don't see it as a big deal.

2020-03-23 12:24 UTC, jespino commented on openApiSync/openApiSync.go
> +		}
Maybe is more clear and compact like this.
```suggestion
		switch node := stmt.(type) {
		case *ast.ExprStmt:
			expr, _ := node.(*ast.ExprStm)
			if call, ok := expr.X.(*ast.CallExpr); !ok {
				continue
			}
			sel := call.Fun.(*ast.SelectorExpr)
			if sel.X.(*ast.Ident).Name == "api" {
				initFunctions = append(initFunctions, sel.Sel.Name)
			}
		case *ast.AssignStmt):
			assgn, _ = node.(*ast.AssignStmt)
			if len(assgn.Lhs) != 1 && !strings.HasPrefix(formatNode(pass.Fset, assgn.Lhs[0]), "api.BaseRoutes") {
				continue
			}
			subRouterName := formatNode(pass.Fset, assgn.Lhs[0])[15:]
			if subRouterName == "ApiRoot" || subRouterName == "Root" {
				continue
			}
			rhs := formatNode(pass.Fset, assgn.Rhs[0])[15:]
			router := rhs[:strings.Index(rhs, ".")]
			path := rhs[strings.Index(rhs, ".")+13 : strings.LastIndex(rhs, ".")-2]
			prefix := ""
			switch router {
			case "ApiRoot":
				prefix = "api/v4"
			case "Root":
				prefix = ""
			default:
				if s, ok := routerPrefixes[router]; ok {
					prefix = s
				} else {
					pass.Reportf(assgn.Rhs[0].Pos(), "cannot find prefix for %s\n", router)
					}
				}
			s := fmt.Sprintf("%v%v", prefix, path)
			s2 := routerPrefixes[subRouterName]
			if s2 != s {
				pass.Reportf(assgn.Rhs[0].Pos(), "PathPrefix doesn't match field comment for field '%s': '%s' vs '%s'\n", subRouterName, s, s2)
			}
		}
```

2020-03-23 12:26 UTC, jespino commented on openApiSync/openApiSync.go
> +		} else if assgn, ok := stmt.(*ast.AssignStmt); ok {
why are we ussing `assgn` insted of `assign`?

2020-03-23 12:30 UTC, jespino commented on openApiSync/openApiSync.go
> +						pass.Reportf(aexpr.Pos(), "Cannot find %v method: %v in OpenAPI 3 spec. (maybe you meant: %v)", h, method, cm.Suggestions(h, false))
I love this `maybe you meant` part!

2020-03-23 12:34 UTC, jespino commented on openApiSync/openApiSync.go
> +				// TODO: make this more generic
A TODO pending here

2020-03-23 12:34 UTC, jespino commented on openApiSync/openApiSync.go
> +				// TODO: make this more generic
another TODO pending here

2020-03-23 12:34 UTC, jespino commented on openApiSync/openApiSync.go
> +				name := aexpr.Fun.(*ast.SelectorExpr).X.(*ast.SelectorExpr).Sel.Name
a bit fragile, but same thing, as before, not a big deal because we have a lot of control over the code.

2020-03-23 12:35 UTC, jespino commented on README.md
> +1. **appErrorWhere** - Makes sure `model.AppError` contains proper `where` field. (**currently disabled**)
This is not used actually, I'm not sure if we should show this in the README.

2020-03-23 12:36 UTC, jespino requested changes
Some improvement suggestion, but in general is looking good.

2020-03-23 15:34 UTC, jespino approved these changes
Nice!

2020-03-23 15:35 UTC, reflog commented
@jespino - awesome. next up - I'll submit a PR to `mattermost-server` that will integrate new `go vet`. Don't worry, you'll be a reviewer on that as well 🤣

2020-03-23 15:35 UTC, merged